# Generated by Django 2.0.5 on 2018-08-31 02:29

import DjangoUeditor.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content_ueditor', DjangoUeditor.models.UEditorField(default='', verbose_name='content')),
                ('content_ckeditor', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
